name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
          -
            name: Checkout 
            uses: actions/checkout@v3
          -
            name: Login to Docker Hub
            env:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_PASSWORD }}
              
            run:
              docker login -u $username -p $password
         
          -
            name: Docker Image build
            run: 
              docker build . -f web/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/devops_project:my-image-$(date +'%c %Y-%m-%d')
              
          -
            name: Docker Image push
            run: 
              docker push ${{ secrets.DOCKER_HUB_USERNAME }}/devops_project:my-image-$(date +'%c %Y-%m-%d')
            
