name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
          -
            name: Checkout 
            uses: actions/checkout@v3
          -
            name: Login to Docker Hub
            env:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
              
            run:
              docker login -u $username -p $password
         
          -
            name: Docker Image build
            run: 
              docker build . --file web/Dockerfile -t d-mac23/devops_project:$(date +%Y-%m-%d)
              
          -
            name: Docker Image push
            run: 
              docker push ${{secrets.DOCKERHUB_HUB_USERNAME}}/devops-project:$(date +%Y-%m-%d)
              
              
              
              
