version: "3"
services:
# app  
  my-app:
    container_name: "my_eshop"
    image: "my_docker1:latest"
    ports: "9091:9091"
    mem_limit: 1024m
    cpus: 1
    
  
# database
  wp-db:
    container_name: "my_postgres"
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=wp
      - POSTGRES_PASSWORD=wp123
      - POSTGRES_DB=e-shop
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
