version: "3"
services:
# app  
  my-app:
    container_name: my_eshop
    image: my-image1:latest
    ports: "9091:9091"
    mem_limit: 512m
    cpus: 1
    
  
# database
  wp-db:
    container_name: my_postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=wp
      - POSTGRES_PASSWORD=wp123
      - POSTGRES_DB=e-shop
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

# prometheus  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
    restart: unless-stopped
    
# grafana
  grafana:
    container_name: grafana
    image: grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
  
  
volumes:
  postgres-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
